baseURL = 'https://markpatricio.com/'
languageCode = 'en-au'
title = 'Mark Patricio'
theme="archie"
copyright = "Â© Mark Patricio"

[params]
  mode="auto"
  description = "ğŸ‘‹ Hey Iâ€™m Mark, and Iâ€™m a DevOps Engineer. â˜ï¸ Iâ€™m interested in all things cloud, CI/CD and automation. ğŸ™ Currently working at Octopus Energy making the world a greener place."

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/sammaritan12"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/markpatricio/"


[[params.social]]
name = "YouTube"
icon = "youtube"
url = "https://www.youtube.com/markpatricio"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
